### ISSUE TITLE
Option questions

### ISSUE THREAD

**Issue by CoralSilver** [andreyan-andreev/node-excel-export#10]
Is it possible for a single sheet to contain multiple headings and specifications?  Or to create a custom top section?

Can I hyperlink to another sheet?

**Comment by andreyan-andreev** [comment]
At this point one sheet supports one heading and one specification. Hyperlinks should be possible, not really sure tough.

**Comment by jaisonka91** [comment]
how to add hyperlink? i didn't saw any documentation for that.
