### ISSUE TITLE
Color problems, all black?

### ISSUE THREAD

**Issue by zeg-io** [andreyan-andreev/node-excel-export#15]
The demo ran completely fine, however Now I've changed up some of the styles but they're all showing as all-black if they have a fill color, even though I'm attempting to use 'FF0000' and the like.

Any direction you could point me in around this would be appreciated.

My font colors are fine.

In addition the `alignment` and `numFmt` properties at https://github.com/protobi/js-xlsx#cell-styles don't seem to work.  Perhaps they've released a more recent version?

**Comment by andreyan-andreev** [comment]
I think js-xlsx uses ARGB codes, so for a white color you would have to write FFFFFFFF, the alpha goes from 00 fully transparent to FF fully opaque.

For the other concerns  that you have its better to check with the js-xlsx guys.

**Comment by zeg-io** [comment]
So the Color issue was my fault.  so you can close that one.
