### ISSUE TITLE
Cell text spanning

### ISSUE THREAD

**Issue by zeg-io** [andreyan-andreev/node-excel-export#16]
I am generating a spreadsheet (thanks for this awesome code, by the way).

However, cell A:1 has a long name, like: `ACME Brick Layer Corporation of America, Incorporated`
Cells B:1 - N:1 are "blank" but have a background color like A:1 (blue)

However A:1 doesn't span into B:1, C:1, D:1 etc.  (Not talking merging, just spanning)

## Set to Blank String

If I set B:1 - N:1's value to `''` the above happens ... if then put my cursor in B:1 and move it out, Cell A:1 starts spanning properly again

![2017-04-06_11-46-11](https://cloud.githubusercontent.com/assets/16530592/24765820/df624278-1abe-11e7-90c6-2be577cb52a1.gif)

## Set to Null
If I set B:1 - N:1's value to `null`, cell A:1 _does_ span into B:1 but there is no longer a background color on those cells!
![2017-04-06_11-49-09](https://cloud.githubusercontent.com/assets/16530592/24765892/21e800ce-1abf-11e7-8914-37cb422613fc.png)

**Comment by andreyan-andreev** [comment]
You may want to merge those cells first, take a look at this fork https://github.com/andreyan-andreev/node-excel-export/issues/6#issuecomment-225615572

Feel free to make a PR if you manage to solve it.

**Comment by zeg-io** [comment]
Pull request pending :) https://github.com/andreyan-andreev/node-excel-export/pull/17

**Comment by zeg-io** [comment]
I didn't follow his method as it struck me as confusing to use.  I updated the README with example code, but the ranges will need to be tweaked to work with the rest of the demo layout.

**Comment by zeg-io** [comment]
Let me know what you think.  I'd love for it to be included in an npm release.  I need my version for a project I'm in the middle of :)

**Comment by andreyan-andreev** [comment]
I have merged your code, let me know if it works now.
