### ISSUE TITLE
Upgrading to version 1.4 causes 'Cell is not defined'

### ISSUE THREAD

**Issue by Ahredmon** [andreyan-andreev/node-excel-export#18]
ReferenceError: cell is not defined
8|reports- |     at sheet_from_array_of_arrays  . . ./node_modules/node-excel-export/lib/excel.js:30:10

I would give you a more verbose log, but it's a company project and I didn't want to expose the structure.

**Comment by andreyan-andreev** [comment]
Can you please update to 1.4.1 and let me know if there are still issues with it.
