### ISSUE TITLE
auto hide cells in ms excel on windows 10

### ISSUE THREAD

**Issue by canabina** [andreyan-andreev/node-excel-export#19]
The main problem is a auto hidden cells in ms excel on windows 10. But another apps like as excel 2007 - 2003 and "Open-Office", show normally. Who else had my problem?

**Comment by mohnishkat** [comment]
This happens when you don't include the width option inside the report specification while exporting!

Btw any idea how I can auto resize the width based on the data length???

**Comment by LokeshBoran** [comment]
@canabina  and @mohnishkat I am also facing same issue in excel 2013 and 2016. It works fine in Ubuntu 16.04 LibreOffice. If you get any solution please reply. Thank :)  :+1:

**Comment by msridar** [comment]
Any solution for this issue

**Comment by canabina** [comment]
@msridar Just hardcode width option in settings
