### ISSUE TITLE
Incredible huge file size

### ISSUE THREAD

**Issue by pts011080** [andreyan-andreev/node-excel-export#22]
I encountered some weird situation.
When I first write the buffer into file it show up the file size like 100MB.
But then it reduced to 15MB after I've open it at Excel and Save it without any modification.

Any idea of this?

**Comment by mohnish4795** [comment]
Getting same problem here, the file is tremendously large and it gets reduced just by re-saving the excel in MS Excel!!
Any Solution regarding this issue?

**Comment by andreyan-andreev** [comment]
Hello guys,
In general this package is nothing more than a thin wrapper around https://github.com/protobi/js-xlsx , so all it gives is little bit more easy way to work the library. I really do not know what may causing the issue, maybe your dataset is too big maybe something else. You can try to use js-xlsx directly and see if this solves the problem.

**Comment by mohnish4795** [comment]
Hey, I don't have a complete solution but kind of a workaround. The reason behind this issue is xlsx-style module which is integrated underneath this module. If I change it from xlsx-style to xlsx then everything seems to work perfectly without any size problem. But then I lose some of the styling functionality!!

@andreyan-andreev Please can you take a look into it.

**Comment by mohnish4795** [comment]
Okay I went into depth of the code to find what was messing things up, and found that the zip compression algorithm is not yet updated in [xlsx-style](https://github.com/protobi/js-xlsx) as it is in [xlsx](https://github.com/SheetJS/js-xlsx). 

So the solution will be to add compression property into write options of this module but it won't work until and unless xlsx-style gets updated..
Check the same issue caused in original module: [Issue](https://github.com/SheetJS/js-xlsx/issues/220)

**Comment by shdb1993** [comment]
Using ExcelJS package solved the issue for me [ExcelJS](https://www.npmjs.com/package/exceljs)
