### ISSUE TITLE
How set the cell's type? eg: can I set number begin with zero?

### ISSUE THREAD

**Issue by jyjin** [andreyan-andreev/node-excel-export#23]
I tried exports some data with this package , but I found every cell's type are 'normal'. I tried to specific a type value in specification, but it didn't work. So how can I change the cell's type from 'normal' to 'text'?

**Comment by leizard** [comment]
I end up having all my cells warning like this:
![image](https://user-images.githubusercontent.com/5291692/33064183-6a32e4f8-ced7-11e7-9693-924af5a9a95f.png)

**Comment by andreyan-andreev** [comment]
In excel when  you want to store a number as text you usually write it like so: `'003`
Note that this is something related to excel not this lib.

**Comment by tpaik18** [comment]
I have the same problem. I tried to add a `'` to the front of the value in the cellFormat function but that just wrote out a literal `'` in front of my value.
