### ISSUE TITLE
missing styles in ms excel

### ISSUE THREAD

**Issue by ThiagoOliveira001** [andreyan-andreev/node-excel-export#30]
My code:
`const styles = {
    headerBlue: {
        fill: {
            fgColor: {
                rgb: '0000FF'
            }

        },
        border: {
            top: { style: 'thin', color: 'FF000000' },
            bottom: { style: 'thin', color: 'FF000000' },
            left: { style: 'thin', color: 'FF000000' },
            right: { style: 'thin', color: 'FF000000' }
        },
        font: {
            color: {
                rgb: 'FFFFFFFF'

            },
            sz: 14,
            bold: true,
            underline: false
        }

    },
    cellYellow: {
        fill: {
            fgColor: {
                rgb: 'FFFF00'
            }
        },
        border: {
            top: { style: 'thin', color: 'FF000000' },
            bottom: { style: 'thin', color: 'FF000000' },
            left: { style: 'thin', color: 'FF000000' },
            right: { style: 'thin', color: 'FF000000' }
        },
        font: {
            bold: true
        },
        alignment: {
            vertical: 'center'
        }
    },
    cellGreen: {
        fill: {
            fgColor: {
                rgb: '98FB98'
            }
        },
        border: {
            top: { style: 'thin', color: 'FF000000' },
            bottom: { style: 'thin', color: 'FF000000' },
            left: { style: 'thin', color: 'FF000000' },
            right: { style: 'thin', color: 'FF000000' }
        },
        font: {
            bold: true,
            vertAlign: true
        },
        alignment: {
            vertical: 'center'
        }
    },
    cellWhite: {
        fill: {
            fgColor: {
                rgb: 'ffffff'
            }
        },
        border: {
            top: { style: 'thin', color: 'FF000000' },
            bottom: { style: 'thin', color: 'FF000000' },
            left: { style: 'thin', color: 'FF000000' },
            right: { style: 'thin', color: 'FF000000' }
        },
        font: {
            bold: false,
            vertAlign: true
        },
        alignment: {
            vertical: 'center'
        }
    },
    cellBeige: {
        fill: {
            fgColor: {
                rgb: 'fffdb8'
            }
        },
        border: {
            top: { style: 'thin', color: 'FF000000' },
            bottom: { style: 'thin', color: 'FF000000' },
            left: { style: 'thin', color: 'FF000000' },
            right: { style: 'thin', color: 'FF000000' }
        },
        font: {
            bold: true,
            vertAlign: true
        },
        alignment: {
            vertical: 'center'
        }
    }`

MS excel error:  Removed Records: Style from /xl/styles.xml.
Normal in google docs or libre-office.

**Comment by endrit-b** [comment]
Is this resolved already? 
@ThiagoOliveira001 did you have to do any workaround?

**Comment by ThiagoOliveira001** [comment]
It´s resolved @endrit-b .
I removed vertAlign of the styles and the problem disappear.
Sorry for my bad english.
