### ISSUE TITLE
Question: Conditional cellStyle?

### ISSUE THREAD

**Issue by rseiffert** [andreyan-andreev/node-excel-export#4]
Is it somehow possible to style a cell based on an attribute of the data? For example:

This is my data
```javascript
name: {value: "A Value",hasChanged:true}
```

and this is my specification
```javascript
name: {
        displayName: 'Name',
        headerStyle: styles.headerDark,
        width: 150,
        cellStyle: function (data) {
          return data.hasChanged ? styles.wrapTextChanged : styles.wrapText;
        },
        cellFormat: function (data) {
          return data.value;
        }
      }
```

**Comment by andreyan-andreev** [comment]
I will implement that, it was a todo but never done it.

**Comment by andreyan-andreev** [comment]
implemented in a237960

**Comment by rseiffert** [comment]
Wow, thank you for implementing!!

**Comment by andreyan-andreev** [comment]
Please let me know if it is working properly.

**Comment by rseiffert** [comment]
I've just installed it via 
`npm install https://github.com/andreyan-andreev/node-excel-export.git` (it's not yet available via npmjs) 
and it works like expected. Thank you very much!
