### ISSUE TITLE
displayName in specification puts object for column header

### ISSUE THREAD

**Issue by YoungPhoenix09** [andreyan-andreev/node-excel-export#5]
Good afternoon,

The displayName attribute for the specification of a column in a sheet is putting [object Object] in the column header instead of the string value I am passing.  I've tried debugging to see what I am doing wrong, but no luck figuring it out.  Upon inspecting the specification object (I call it structure), I saw the following for one of the columns:

`structure: {
    SellerLoanNo: {
        cellFormat: function replaceNull(...)...,
        displayName: "Seller Loan #",
        width: 120
    }
}`

Is there any reason why a value for the displayName would output an object in the spreadsheet?  In case it matters, I am using the value from an array's forEach method...but I am 100% it is giving a string for the value.

Thanks!

**Comment by andreyan-andreev** [comment]
As there is no way for me to guess what exactly is going on. I would suggest you to take a look here:

https://github.com/andreyan-andreev/node-excel-export/blob/master/index.js#L30

and probably do something like:

```javascript
console.log(col, typeof  specification[col].displayName,  specification[col].displayName)
```

This will most likely reveal the problem to you.

**Comment by fhemberger** [comment]
Had the same problem. Use the example from the readme and adjust `specification`:

```js
var specification = {
  // This renders fine
  customer_name: {
    displayName: 'Customer',
    headerStyle: styles.headerDark
  },
  // This results in [object Object]
  status_id: {
    displayName: 'Status'
  },
  …
```

It seems you **need** to provide `headerStyle` for the header to render properly.

**Comment by andreyan-andreev** [comment]
Thank you both for reporting this. 
@fhemberger good catch, I will fix it asap.

**Comment by xwang1024** [comment]
I think the default value of headerStyle is {} , not empty string. @frenchbread

**Comment by 70m43** [comment]
Add that after specification :
`
var styles = {  headerBlank: { fill: { patternType: "none"  }  } }
  for (var i = 0; i < Object.keys(specification).length; i++) {
    specification[Object.keys(specification)[i]]["headerStyle"] = styles.headerBlank
    specification[Object.keys(specification)[i]]["displayName"] = " "
  }
`

**Comment by faq885** [comment]
This is still happening to me :(
