### ISSUE TITLE
Merge cells

### ISSUE THREAD

**Issue by ficzusistvan** [andreyan-andreev/node-excel-export#6]
Hi!

I can't seem to find how to merge table cells in the header row. Is this feature supported?

**Comment by YoungPhoenix09** [comment]
It's not implemented by this package, however it is supported by one of the underlying packages.  I was able to implement in a version I created.  When I have a moment I can see about adding in detail what I did to do this.

**Comment by ficzusistvan** [comment]
Hi YoungPhoenix09!

It would be nice to have an example. This is a blocking issue for me right now.

**Comment by YoungPhoenix09** [comment]
Alright ficzusistvan, 

Got a quick fix up for you.  I created a [fork](https://github.com/YoungPhoenix09/node-excel-export) that includes the underlying packages with my modifications to them to implement cell merging.  Basically, anywhere you are specifying an object with a value and style, you can also add a "merge" attribute with an integer value (i.e. merge: 0).  All cells with the same number will be merged together.

**Comment by ficzusistvan** [comment]
Thanks YoungPhoenix09!

It is working as expected! In my opinion this really should be a feature included in the main branch.

**Comment by YoungPhoenix09** [comment]
Glad it worked for you and that I could help!  I'd be happy to help with adding to the main.  I'm no github guru, but I'm good with providing whatever is need to get it included.

**Comment by andreyan-andreev** [comment]
@YoungPhoenix09 feel free to file a merge request, I will make more people benefit from your fix.

**Comment by andreyan-andreev** [comment]
The package has been updated to support merging. Please take a look at the updated example.
