### ISSUE TITLE
Cell style doesn't work for large records

### ISSUE THREAD

**Issue by tohammad** [andreyan-andreev/node-excel-export#7]
![th4u6](https://cloud.githubusercontent.com/assets/5390209/16036682/a600fcbc-323a-11e6-85be-b217fdcfae74.png)

Getting above error after styling cells, probably the cell style object has been created for each cell.
I have around 100,000 records in grid.

**Comment by andreyan-andreev** [comment]
The problem seems to be with the underlying package https://github.com/protobi/js-xlsx
This must be the more appropriate place for your question. Feel free to reopen the issue if you feel otherwise.
